<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TimeTracker</AssemblyName>
    <RootNamespace>TimeTracker</RootNamespace>
    <TargetPlatformMoniker>Windows,Version=7.0</TargetPlatformMoniker>
    <TargetPlatformDisplayName>Windows</TargetPlatformDisplayName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
  </ItemGroup>
</Project>
